eureka:
  instance:
    hostname: 192.168.0.108
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 1
  client:
    registryFetchIntervalSeconds: 1
    register-with-eureka: false
    fetch-registry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
spring:
  security:
    oauth2:
      client:
        provider:
          keycloak:
            user-name-attribute: preferred_username
            issuer-uri: http://192.168.0.120:8082/realms/selmag
        registration:
          keycloak:
            client-id: eureka-server
            client-secret: 2O42S8Ak4RXUxtovyT8lLsyGjIpPFoBH
            scope:
              - openid
      resourceserver:
        jwt:
          issuer-uri: http://192.168.0.120:8082/realms/selmag