spring:
  cloud:
    gateway:
      routes:
        - id: catalog-service-route
          uri: lb://selmag-catalogue-service
          predicates:
            - Host=catalogue.api.kush.corn.192.168.0.108.nip.io
        - id: feedback-service-route
          uri: lb://selmag-feedback-service
          predicates:
            - Host=feedback.api.kush.corn.192.168.0.108.nip.io
        - id: manager-app-route
          uri: lb://selmag-manager-app
          predicates:
            - Host=manager.selm.ag.192.168.0.108.nip.io
        - id: customer-app-route
          uri: lb://selmag-customer-app
          predicates:
            - Host=customer.selm.ag.192.168.0.108.nip.io
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.0.120:8082/realms/selmag
      client:
        provider:
          keycloak:
            issuer-uri: http://192.168.0.120:8082/realms/selmag
        registration:
          discovery:
            provider: keycloak
            authorization-grant-type: client_credentials
            client-id: api-gateway
            client-secret: RJOuO8i9Ay2Xg7S5634bq8FUkZVdx3w5
            scope:
              - discovery
  application:
    name: selmag-api-gateway
  boot:
    admin:
      client:
        enabled: false
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  zipkin:
    tracing:
      endpoint: http://192.168.0.120:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 1
    hostname: 192.168.0.108
  client:
    service-url:
      defaultZone: http://192.168.0.108:8761/eureka/
    registryFetchIntervalSeconds: 1
