spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://192.168.0.120:8082/realms/selmag
      client:
        provider:
          keycloak:
            issuer-uri: http://192.168.0.120:8082/realms/selmag
            user-name-attribute: preferred_username
        registration:
          keycloak:
            authorization-grant-type: client_credentials
            scope:
              - metrics
            client-id: admin-service
            client-secret: AniOsr2LTXVVb9oSZRF1JT23tyAPC1Z0
          login:
            provider: keycloak
            scope:
              - metrics
              - openid
            client-id: admin-service
            client-secret: AniOsr2LTXVVb9oSZRF1JT23tyAPC1Z0
          discovery:
            provider: keycloak
            client-id: admin-service
            client-secret: AniOsr2LTXVVb9oSZRF1JT23tyAPC1Z0
            authorization-grant-type: client_credentials
            scope:
              - discovery
  # Увеличиваем interval, lifetime и timeout для проверки статуса
  # для корректной работы монитора в Spring Boot Admin
  # из-за проблем с mongo db в сервисе feedback
  boot:
    admin:
      monitor:
        status-lifetime: 20000
        status-interval: 15000
        default-timeout: 20000
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus
eureka:
  client:
    service-url:
      defaultZone: http://192.168.0.108:8761/eureka/
    registryFetchIntervalSeconds: 1
    register-with-eureka: false
  instance:
    hostname: 192.168.0.108
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 1